### PR TITLE
refactor(lib): remove module wrapper && minor cleanups

### LINKED ISSUE #11: [fix]: uglifyjs: not found

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
### `Issues`

- Fixes #11

### CODE REVIEW

**Comment by GitScrum** [comment]
@michael-ciniawsky please resolve conflict and revert commit 369e1a4 because issue #11 fixed

**Comment by michael-ciniawsky** [comment]
@GitScrum You mean to remove the rollup setup with https://github.com/posthtml/posthtml-render/commit/369e1a4f982c6166b5839fcbf20125a907c5f3b8 right?

**Comment by GitScrum** [comment]
@michael-ciniawsky no, i mean `refactor(lib): remove module wrapper && minor cleanups` now commin 4dc4a81

**Comment by michael-ciniawsky** [comment]
I added the module wrapper via `rollup` instead => 

```
posthtml-render
|– lib
| |– index.js (NodeJS)
| |– browser.min.js (Rollup (Wrapper) && Uglify)
| |– browser.js.map (Source Map)
|
|– rollup.config.js
```

**package.json**
```
{
  "main": "lib",
  "browser": "lib/browser.min.js"  (webpack, rollup etc will pick this up)
}
```

**Comment by GitScrum** [comment]
@michael-ciniawsky ok, I was thinking of doing this as a separate task. Fix tests please.

**Comment by michael-ciniawsky** [comment]
> I was thinking of doing this as a separate task

kk I can also remove the rollup setup and open a separate PR asap if you prefer ? As long as I don't need to add the current module wrapper back then... 😛 

> Fix tests please.

Tests are only failing because of  `nyc@latest` requiring `node >= v4.0.0`. I need to downgrade it 😞 mom...

**Comment by michael-ciniawsky** [comment]
@GitScrum Done

**Comment by GitScrum** [comment]
@voischev approve ?

**Pull request merged**
