### PR TITLE
add options.maxLineLength support

### PR DESCRIPTION
**Pull request by selbyk**
- minor version: adds feature, doesn't break current configs
  - breaks CSS at safe points into newlines if past maxLineLength
  - breaks HTML at safe points into newlines if past maxLineLength

TODO:
 Break text content on whitespace (except prevs)

Issue: https://github.com/posthtml/posthtml-render/issues/3

### CODE REVIEW

**Comment by selbyk** [comment]
Tests should be passing, the build is failing on travis for an unrelated reason on all 3 node binaries: `sh: 1: uglifyjs: not found`. 

We need a way to limit line length, and this seemed like a good place to start. Any thoughts?

Thanks for your time

**Comment by selbyk** [comment]
Are there any maintainers that could provide some feedback?  We'd love to know if this PR has a chance of being merged, and if so, what steps lay ahead.

We still need lots of time to test the HTML/CSS we generate so that that are no breaks in our interactivity and reporting.  So there's no big rush, but I would personally love to continue using this original branch instead of forking our own.

**Comment by voischev** [comment]
hi 👋 why not plugin for posthtml? 
https://github.com/posthtml/posthtml-render/issues/3#issuecomment-181423897

**Comment by voischev** [comment]
posthtml-parser + posthtml-render should be merge in posthtml in future

**Pull request closed without merging**
