### PR TITLE
feat: allow regexps in singleTags option

### PR DESCRIPTION
**Pull request by maciej-ka**
This will enable leaving tags like `<%=title%>` unchanged by passing an option `singleTags: [/^%.*%$/]`. (Currently, they are transformed into `<%=title%></%=title%>`.

Enables to solve: https://github.com/parcel-bundler/parcel/issues/544

### CODE REVIEW

**Comment by GitScrum** [comment]
@maciej-ka Hi, thanks for you PR. Add description on readme.

**Comment by maciej-ka** [comment]
Docs added and conflict resolved.

**Comment by maciej-ka** [comment]
🎉

**Comment by GitScrum** [comment]
@voischev I need to publish the first `v1.0.7`, but I do not have a home to `npm` (

**Pull request merged**
